# Generated by Django 4.2.3 on 2023-07-31 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_user_is_admin_alter_user_is_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
    ]
